"""empty message

Revision ID: 465fc2d12cee
Revises: 
Create Date: 2019-06-28 16:54:28.166990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465fc2d12cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('COMPANY')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COMPANY',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.Column('AGE', sa.INTEGER(), nullable=False),
    sa.Column('ADDRESS', sa.CHAR(length=50), nullable=True),
    sa.Column('SALARY', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('roles')
    op.drop_table('users')
    # ### end Alembic commands ###
